<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Sessoes\**" />
    <EmbeddedResource Remove="Sessoes\**" />
    <None Remove="Sessoes\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Class1.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.11" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Adicionais\Entidades\" />
    <Folder Include="Adicionais\Comandos\" />
    <Folder Include="EnderecoClientes\Repositorios\Filtros\" />
  </ItemGroup>

</Project>
