<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Class1.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Empresas\Servicos\" />
    <Folder Include="Empresas\Repositorios\" />
    <Folder Include="EnderecosEmpresas\Servicos\" />
    <Folder Include="EnderecosEmpresas\Repositorios\" />
    <Folder Include="HorariosFuncionamento\Servicos\" />
    <Folder Include="HorariosFuncionamento\Repositorios\" />
  </ItemGroup>

</Project>
